galaxy_info:
  author: Trungdc
  description: Exercise 04 Role
  company: VNPT

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

 
  platforms:
  - name: EL
    versions:
    - "7"

  - name: Ubuntu
    versions:
    - "bionic"  


 # galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

#dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  